# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Features
    url: /#features
    weight: 20
  - name: Solutions
    url: /#solutions
    weight: 30
  - name: Resources
    weight: 40
    hasChildren: true
  - parent: Resources
    name: Blog
    url: blog/
  - parent: Resources
    name: media coverage
    url: media_coverage/
  - parent: Resources
    name: academic references
    url: academic_references/    
  - parent: Resources
    name: NGOs
    url: ngo/       
  - parent: Resources
    name: podcasts
    url: podcasts/     
  - parent: Resources
    name: corporations
    url: corporations/
  - parent: Resources
    name: take action
    url: take_action/       